DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS author;
CREATE TABLE author(id BIGINT PRIMARY KEY,name VARCHAR(255)NOT NULL,email VARCHAR(255));
CREATE TABLE book(id BIGINT PRIMARY KEY,title VARCHAR(255)NOT NULL,isbn VARCHAR(50),price DOUBLE,publishedAt VARCHAR(50),author_id BIGINT,CONSTRAINT fk_author FOREIGN KEY 
(author_id)REFERENCES author(id));